arkeotouim_proj/touim/urls.py
from django.urls import path
from .views import (
    SitesDetailView, 
    SitesUpdateView,
    SitesDeleteView,
    MobiliersListView,
    MobiliersDeleteView
    )
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='touim-home'),  #for search
    path('site/<int:pk>/', SitesDetailView.as_view(), name='site-detail'),
    path('site/new/', views.site_create, name='site_create'),
    path('site/<int:pk>/update/', SitesUpdateView.as_view(), name='site-update'),
    path('site/<int:pk>/delete/', SitesDeleteView.as_view(), name='site-delete'),
    path('mobilier', MobiliersListView.as_view(), name='touim-mobilier'),
    path('site/<int:site_id>/mobilier_create/', views.mobilier_create, name='mobilier_create'),
    path('mobilier/<int:pk>/delete/', MobiliersDeleteView.as_view(), name='mobilier-delete'),
    path('about/', views.about, name='touim-about'),
    path('layers/', views.layers, name='touim-layers'),
    path('layers2/', views.layers2, name='touim-layers2'),
    path('carto/', views.carto, name='touim-carto'),
    path('biblio/', views.biblio, name='touim-biblio'),
    path('biblio/biblio_create/', views.biblio_create, name='biblio_create')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

arkeotuim/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('touim.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

touim/urls.py
from django.urls import path
from .views import (
    SitesDetailView, 
    SitesUpdateView,
    SitesDeleteView,
    MobiliersListView,
    MobiliersDeleteView
    )
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='touim-home'),  #for search
    path('site/<int:pk>/', SitesDetailView.as_view(), name='site-detail'),
    path('site/new/', views.site_create, name='site_create'),
    path('site/<int:pk>/update/', SitesUpdateView.as_view(), name='site-update'),
    path('site/<int:pk>/delete/', SitesDeleteView.as_view(), name='site-delete'),
    path('mobilier', MobiliersListView.as_view(), name='touim-mobilier'),
    path('site/<int:site_id>/mobilier_create/', views.mobilier_create, name='mobilier_create'),
    path('mobilier/<int:pk>/delete/', MobiliersDeleteView.as_view(), name='mobilier-delete'),
    path('about/', views.about, name='touim-about'),
    path('layers/', views.layers, name='touim-layers'),
    path('layers2/', views.layers2, name='touim-layers2'),
    path('carto/', views.carto, name='touim-carto')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

arkeotouim_proj/touim/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from PIL import Image

class Biblio(models.Model):
    id_biblio = models.IntegerField(primary_key=True)
    titre = models.CharField(max_length=250)
    autor = models.CharField(max_length=250)
    year = models.IntegerField()
    tip = models.CharField(max_length=50, default='')
    coll = models.CharField(max_length=250, default='')
    edition = models.CharField(max_length=250, default='')
    pages = models.CharField(max_length=30, default='')

    def __str__(self):
        return self.titre

    class Meta:
        ordering = ('titre',)


class Sites(models.Model):
    id = models.IntegerField(primary_key=True)
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    oper = models.CharField(max_length=250)
    sitename = models.CharField(max_length=500)
    infor = models.CharField(max_length=9000, default='')
    descr = models.CharField(max_length=9000, default='')
    site_logo = models.FileField(default='pasdimage.png')
    periode = models.CharField(max_length=300)
    coordx = models.FloatField()
    coordy = models.FloatField()
    paleol = models.CharField(max_length=300)
    bronze = models.CharField(max_length=30)
    discovered = models.IntegerField()
    iron = models.CharField(max_length=30)
    mesol = models.CharField(max_length=30)
    middle_age = models.CharField(max_length=30)
    neol1 = models.CharField(max_length=30)
    neol2 = models.CharField(max_length=30)
    neol3 = models.CharField(max_length=30)
    passport = models.CharField(max_length=20)
    topo = models.FileField(default='pasdimage.png')
    biblio = models.ManyToManyField(Biblio)

    def __str__(self):
        return self.sitename

    # def __str__(self):
    #     return f'{self.id}'  # user.username
    
    class Meta:
        ordering = ('sitename',)

    def get_absolute_url(self):
        return reverse('site-detail', kwargs={'pk':self.pk})


class Mobiliers(models.Model):
    site = models.ForeignKey(Sites, on_delete=models.CASCADE)
    mob_nom = models.CharField(max_length=250)
    mob_logo = models.FileField(default='pasdimage.png')
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)

    def __str__(self):
        return self.mob_nom

class Admini(models.Model):
    id_admini = models.IntegerField(primary_key=True)
    categ = models.CharField(max_length=250)
    vid = models.CharField(max_length=100)
    vid_comm = models.CharField(max_length=250)
    utilisation = models.CharField(max_length=250)
    herit = models.CharField(max_length=50)
    infor = models.CharField(max_length=9000, default='') # à supprimer vue qu'on a ces champs dans le table Sites
    descr = models.CharField(max_length=9000, default='') # à supprimer vue qu'on a ces champs dans le table Sites
    site = models.ForeignKey(Sites, on_delete=models.CASCADE)

    def __str__(self):
        return self.id_admini


class Staticmap(models.Model):
    id_map = models.IntegerField(primary_key=True)
    mapname = models.CharField(max_length=250)
    mapfile = models.FileField()
    autor = models.CharField(max_length=250)

    def __str__(self):
        return self.mapname


class Images(models.Model):
    id_img = models.IntegerField(primary_key=True)
    imgname = models.CharField(max_length=250)
    imgfile = models.FileField(default='')
    author = models.CharField(max_length=250)

    def __str__(self):
        return self.imgname

touim/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image


class Sites(models.Model):
    id_site = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    sitename = models.CharField(max_length=500)
    oper = models.CharField(max_length=250)
    descr = models.CharField(max_length=9000, default='')
    site_img = models.FileField(default='pasdimage.png')
    date = models.CharField(max_length=300)

    def __str__(self):
        return self.sitename

    # def __str__(self):
    #     return f'{self.id}'  # user.username
    
    class Meta:
        ordering = ('sitename',)

    def get_absolute_url(self):
        return reverse('site-detail', kwargs={'pk':self.pk})


class Mobiliers(models.Model):
    site = models.ForeignKey(Sites, on_delete=models.CASCADE)
    mob_nom = models.CharField(max_length=250)
    mob_img = models.FileField(default='pasdimage.png')
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)

    def __str__(self):
        return self.mob_nom

class Admini(models.Model):
    id_admini = models.IntegerField(primary_key=True)
    categ = models.CharField(max_length=250)
    vid = models.CharField(max_length=100)
    vid_comm = models.CharField(max_length=250)
    utilisation = models.CharField(max_length=250)
    herit = models.CharField(max_length=50)
    infor = models.CharField(max_length=9000, default='') # à supprimer vue qu'on a ces champs dans le table Sites
    descr = models.CharField(max_length=9000, default='') # à supprimer vue qu'on a ces champs dans le table Sites
    site = models.ForeignKey(Sites, on_delete=models.CASCADE)

    def __str__(self):
        return self.id_admini


class Staticmap(models.Model):
    id_map = models.IntegerField(primary_key=True)
    mapname = models.CharField(max_length=250)
    mapfile = models.FileField()
    autor = models.CharField(max_length=250)

    def __str__(self):
        return self.mapname


class Images(models.Model):
    id_img = models.IntegerField(primary_key=True)
    imgname = models.CharField(max_length=250)
    imgfile = models.FileField(default='')
    author = models.CharField(max_length=250)

    def __str__(self):
        return self.imgname

touim/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Sites, Mobiliers
from django.utils.translation import gettext_lazy as _


class SiteForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["descr"].widget = forms.Textarea()
        self.fields['descr'].widget.attrs.update({'class': 'narrow-select'})

    class Meta:
        model = Sites
        fields = '__all__'
        exclude = ['id_site', 'user', 'biblio']
        labels = {
            'sitename':_('Name of site'),
            'oper':_('Type of operation'),
            'descr': _('Description'),
            'site_img': _('Image'),
            'date': _('Dates'),
        }


class MobiliersCreateForm(forms.ModelForm):

    class Meta:
        model = Mobiliers
        fields = ['mob_nom', 'mob_img']
        labels = {
            'mob_nom':_('Name'),
            'mob_img':_('Image')
        }
        help_texts = {
            'mob_nom': _('Some useful help text.'),
        }

arkeotouim_proj/touim/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
    ListView, 
    DetailView, 
    CreateView,
    UpdateView,
    DeleteView
    )
from .models import Sites, Biblio, Staticmap, Mobiliers, Images
from .forms import SiteForm, MobiliersCreateForm, BiblioCreateForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator


IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def home(request):
    sites = Sites.objects.filter()
    mobilier_results = Mobiliers.objects.all()
    query = request.GET.get("q")
    if query:
        sites = sites.filter(
            Q(sitename__icontains=query) |
            Q(oper__icontains=query)
        ).distinct()
        mobilier_results = mobilier_results.filter(
            Q(mob_nom__icontains=query)
        ).distinct()
        return render(request, 'touim/home.html', {
            'sites': sites,
            'mobiliers': mobilier_results,
        })
    else:
        paginator = Paginator(sites, 10)
        page = request.GET.get('page')
        sites = paginator.get_page(page)
        return render(request, 'touim/home.html', {'sites': sites})


class SitesDetailView(DetailView):
    model = Sites
    mobiliers = Mobiliers.objects.all()
    biblios = Biblio.objects.all()


def site_create(request):
    s_form = SiteForm(request.POST or None, request.FILES or None)
    if s_form.is_valid():
        site = s_form.save(commit=False)
        site.user = request.user
        site.site_logo = request.FILES['site_logo']
        site.topo = request.FILES['topo']
        file_type = site.site_logo.url.split('.')[-1]
        file_typetopo = site.topo.url.split('.')[-1]
        file_type = file_type.lower()
        file_typetopo = file_typetopo.lower()
        if file_type and file_typetopo not in IMAGE_FILE_TYPES:
            context = {
            'site': site,
            's_form': s_form,
            'error_message': 'Image file must be PNG, JPG, or JPEG',
            }
            return render(request, 'touim/sites_create.html', context)
        site.save()
        object = site
        return render(request, 'touim/sites_detail.html', {'object':object})
    context = {"s_form": s_form,}
    return render(request, 'touim/site_create.html', context)


# fonctionne mais ne modifie pas les images:
class SitesUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Sites
    fields = '__all__'
    exclude = ['user', 'biblio']


    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        site = self.get_object()
        if self.request.user == site.user:
            return True
        return False


class SitesDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Sites
    success_url = '/'

    def test_func(self):
        site = self.get_object()
        if self.request.user == site.user:
            return True
        return False


class MobiliersListView(ListView):
    model = Mobiliers
    template_name = 'touim/mobilier.html'  # pattern: <app>/<model>_<viewtype>.html
    context_object_name = 'mobiliers'
    ordering = ['-date_posted']
    paginate_by = 4


def mobilier_create(request, site_id):
    m_form = MobiliersCreateForm(request.POST or None, request.FILES or None)
    site = get_object_or_404(Sites, pk=site_id)
    if m_form.is_valid():
        sites_mobiliers = site.mobiliers_set.all()
        for s in sites_mobiliers:
            if s.mob_nom == m_form.cleaned_data.get("mob_nom"):
                context = {
                    'site':site,
                    'm_form':m_form,
                    'error_message':'You already added that object'
                }
                return render(request, 'touim/mobilier_create.html', context)
        mobilier = m_form.save(commit=False)
        mobilier.site = site
        mobilier.mob_logo = request.FILES['mob_logo']
        file_type = mobilier.mob_logo.url.split('.')[-1]
        file_type = file_type.lower()
        object = site
        if file_type not in IMAGE_FILE_TYPES:
            context = {
                'site':'site',
                'm_form':'m_form',
                'error_message': 'Image file must be PNG, JPG or JPEG'
            }
            return render(request, 'touim/mobilier_create.html', context)

        mobilier.save()
        return render(request, 'touim/sites_detail.html', {'object':object})
    context = {
        'site':site,
        'm_form':m_form,
    }
    return render(request, 'touim/mobilier_create.html', context)


class MobiliersDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Mobiliers
    success_url = '/'
    sites = Sites.objects.all()

    def test_func(self):
        mobilier = self.get_object()
        if self.request.user == mobilier.user:
            return True
        return False


def about(request):
    images = Images.objects.all()
    return render(request, 'touim/about.html', {'title':'About', 'images':images})


def layers(request):
    return render(request, 'touim/layers.html')


def layers2(request):
    sites = Sites.objects.all()
    return render(request, 'touim/layers2.html', {'sites':sites})


def carto(request):
    cartos = Staticmap.objects.all()
    return render(request, 'touim/cartography.html', {'cartos':cartos})


def biblio(request):
    biblios = Biblio.objects.all()
    return render(request, 'touim/bibliography.html', {'biblios':biblios})


@login_required
def biblio_create(request):
    if request.method == "POST":
        form = BiblioCreateForm(request.POST)
        if form.is_valid():
            biblio = form.save(commit=False)
            biblio.save()
            biblios = Biblio.objects.filter()
            return render(request, 'touim/bibliography.html',
                          {'biblios': biblios})
    else:
        form = BiblioCreateForm()
    return render(request, 'touim/biblio_create.html', {'form': form})


def biblio_delete(request, site_id, biblio_id):
    site = get_object_or_404(Sites, pk=site_id)
    mobilier = Mobiliers.objects.get(pk=mobilier_id)
    mobilier.delete()
    return render(request, 'touim/detail.html', {'site': site})

touim/templates/touim/about.html
{% extends "touim/base.html" %}
{% block about_active %}active{% endblock %}
{% block content %}
<div class="sites-container container-fluid" style="background-color: #252B35;">
    <div class="row">
        <div class="col-sm-12">


    <div class="row">
        <!-- Left sidebar: -->
        <div class="col-sm-6 col-md-6" style="color: gray;">
                <div class="panel-body" style="margin-left: 30px;">
                    <h2 class="titly">This is Arkeotuym application</h2>
                    <p>Это приложение позволяет записывать и хранить данные по археологии Якутии (стоянки, найденные на них артефакты, библиографические источники, карты и графики).</p>
                <ul>ArkeoTuym также включает в себя интекрактивную карту, которая: 
                    <li>визуализирует географическое положение памятников археологии</li>
                    <li>предоставляет возможность отображения фоновых карт по выбору</li>
                    <li>имеет функцию поиска стоянок по их названию</li>
                    <li>содержит краткую информацию о каждой стоянке</li>
                </ul>
                <h4><b>Как пользоваться ресурсом?</b></h4>
                <p>Сперва нужно создать стоянку, нажав на зелёную кнопку на главной странице. После добавления стоянки, можно добавить найденный на ней артефакт и библиографический источник</p>
                <h4>Характеристики загружаемых данных</h4>
                <ul>
                    <li>Добавляемые изображения должны быть в формате .jpg, .gif, или .png</li>
                    <li>Вес одиного файла не должен превышать 2Мб.</li>
                </ul>
                <h4><b>Attention !</b></h4>
                <p>В этом приложении использованы псевдоданные. Подлинные георгафические координаты археологических стоянок заменены на местоположения, выбранные случайным образом.</p>
                </div>
            <!-- </div> -->
        </div>
        <!-- Right sidebar (images + info admini) -->
        <div class="col-sm-6 col-md-6">
            <div class="panel-body" style="margin-top: 30px;">
                {% for image in images.all %}
                    {% if image.id_img == 1 %}
                        <img src="{{ image.imgfile.url }}" style="height: 410px;">
                    {% else %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="panel-body" style="color: gray;">
        <hr style="width:55%;" />
        <h3 class="contenutext ct-justy titly">ATTRIBUTIONS</h3>
        <hr style="width:2%;" />
        <div class="contenutext espacy">
            <p style="text-align: center;">Duis aute irure. Lorem ipsum dolor sit amet, consectetur adipiscing -- https://loremipsum.io/</p>
        </div>
        <hr style="width:55%;" />
        <h3 class="contenutext ct-justy titly">CONTACTS</h3>
        <hr style="width:2%;" />
        <div class="contenutext ct-justy espacy">
            <span class="glyphicon glyphicon-phone-alt"></span> +7 900 000 00 00 -- 
            <span class="glyphicon glyphicon-envelope"></span> kte.ent@gmail.com   
        </div>
    </div>
        {% for image in images.all %}
            {% if image.id_img == 2 %}
                <img src="{{ image.imgfile.url }}" style="width:100%;margin-top:20px;float: right;">
            {% else %}
            {% endif %}
        {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

touim/templates/touim/biblio_create.html
{% extends "touim/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <!-- Left Site Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <i class="glyphicon glyphicon-book" style="font-size:150px;text-shadow:2px 2px 4px #000000;"></i>
                    <i class="glyphicon glyphicon-plus-sign" style="font-size:50px;text-shadow:2px 2px 4px #000000;padding: 15px;margin-top: 10px;"></i>
                </div>
            </div>
        </div>
        <!-- Right Mobilier Info -->
        <div class="col-sm-8 col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add publication</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="site" value="{{ site }}">
                        {% include 'touim/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

touim/templates/touim/bibliography.html
{% extends "touim/base.html" %}
{% block biblios_active %}active{% endblock %}
{% block content %}
<div class="container">
<div class="sites-container container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="add-site">
                <a href="{% url 'biblio_create' %}" style="color: white;">
                    <button class="btn btn-success">
                        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>&nbsp; Add publication
                    </button>
                </a>
            </div>
            <h3 class="titre-page">Publications related to the sites of TValley</h3>
            <div class="panel panel-default" style="background-color: #11141B; color: gray;">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr style="color: #ccc;">
                                <th>Title</th>
                                <th>Collection</th>
                                <th>Author</th>
                                <th>Year</th>
                            </tr>
                        </thead>
                        <tbody style="color: #ccc;">
                            {% for biblio in biblios %}
                                <tr>
                                    <td>{{ biblio.titre }}</td>
                                    <td>{{ biblio.coll }}</td>
                                    <td>{{ biblio.autor }}</td>
                                    <td>{{ biblio.year }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
</div>
</div>
</div>

{% endblock content %}

touim/templates/touim/sites_detail.html
{% extends "touim/base.html" %}
{% block content %}
<div class="container-fluid songs-container">
    <div class="row">
        <!-- Left sidebar: -->
        <div class="col-sm-8 col-md-9">
            <div class="panel panel-default" style="background-color: #A09571;"> <!--#E3C67D/ #EBEAEC -->
                <div class="panel-body">
                    <!-- update and delete site -->
                    
                        <p style="text-align: right;">
                            <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'site-update' object.id_site %}">Редактировать</a>
                            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'site-delete' object.id_site %}">Удалить</a>
                        </p>
                                     
                    <p><h2>{{ object.sitename }}</h2></p>
                    <p><b>Период: </b>{{ object.date }}</p>
                    <p><b>Описание: </b>{{ object.descr }}</p>
                </div>
            </div>

            <!-- Mobiliers: -->
            <div class="panel panel-default">
                <div class="panel-body" style="background-color: #C78E50; color: black;">
                    <h4 style="color: black;">Artefacts of site <b>{{ object.sitename }}</b></h4>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Image</th>
                            <th>Archaeological culture</th>
                            <th>Delete</th>
                            <!-- <th>Удалить</th> -->
                        </tr>
                        </thead>
                        <tbody>
                        {% for mobilier in object.mobiliers_set.all %}
                            <tr>
                                <td>{{ mobilier.mob_nom }}</td>
                                <td>
                                    <a target="_blank" href="{{ mobilier.mob_img.url }}">
                                        <button type="button" class="btn btn-default btn-xs">
                                            <span class="glyphicon glyphicon-eye-open"></span>&nbsp; View
                                        </button>
                                    </a>
                                </td>
                                <td>Middle neolith culture</td>
                                <td>
                                {% if object.user == user %}
                                    <!-- <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'mobilier-delete' mobilier.id %}">Delete</a> -->
                                    <!-- <a class="btn btn-primary btn-sm mt-1 mb-1" href="#">Update</a> -->
                                    <a href="{% url 'mobilier-delete' mobilier.id %}">
                                        <button class="btn btn-default">
                                            <span class="glyphicon glyphicon-trash"></span></button>
                                        </a>      
                                {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <ul class="nav nav-pills" style="margin-bottom: 10px;">
                        <div role="presentation">
                        {% if object.user == user %}
                            <a href="{% url 'mobilier_create' object.id_site %}" style="color: white;">
                                <button type="button" class="btn" style="background-color: #A7522D">Add new artifact
                                </button>
                            </a>
                        {% endif %}
                        </div>
                    </ul>
                </div>
            </div>
        </div>
        <!-- Right sidebar (images + info admini) -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default" style="background-color: #A09571;">
                <div class="panel-body">
                        {% if object.site_img %}
                            <a  target="_blank" href="{{ object.site_img.url }}">
                                <img src="{{ object.site_img.url }}" class="img-responsive"/>
                            </a>
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    <h5><i>Фото местности</i></h5>
                </div>
                <div class="panel-body">
                        {% for admini in object.admini_set.all %}
                            <p><b>Category of site: </b>{{ admini.categ }}</p>
                            <p><b>Type: </b>{{ admini.vid_comm }}</p>
                            <p><b>Usage: </b>{{ admini.utilisation }}</p>
                        {% endfor %} 
                </div>
            </div>
        </div>
    </div>
</div> <!-- close site-container div -->
<h3 class="please">Please, login with postgres nickname == FIXME</h3>
{% endblock content %}